# Read the libraries and data

In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [70]:
import os

In [71]:
data = pd.read_csv('Blend.csv')
data2 = pd.read_csv('Blend.csv')

In [72]:
data.head()

AF    AV    AC   SR     CL   FSO   TSO       D    PH     S   OH  Target  \
0   7.4  0.70  0.00  1.9  0.076  11.0  34.0  0.9978  3.51  0.56  9.4       5   
1   7.8  0.88  0.00  2.6  0.098  25.0  67.0  0.9968  3.20  0.68  9.8       5   
2   7.8  0.76  0.04  2.3  0.092  15.0  54.0  0.9970  3.26  0.65  9.8       5   
3  11.2  0.28  0.56  1.9  0.075  17.0  60.0  0.9980  3.16  0.58  9.8       6   
4   7.4  0.70  0.00  1.9  0.076  11.0  34.0  0.9978  3.51  0.56  9.4       5   

   type  
0     0  
1     0  
2     0  
3     0  
4     0

In [73]:
target = data['type']

In [74]:
data = data.drop(['type'],axis=1)

In [75]:
from sklearn.model_selection import train_test_split

In [76]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.30, random_state=42)

# Decision Tree

In [77]:
from sklearn.tree import DecisionTreeClassifier

In [78]:
dtree = DecisionTreeClassifier()

In [79]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

# Predictions and Evaluations

In [80]:
predictions_train = dtree.predict(X_train)

In [81]:
predictions_test = dtree.predict(X_test)

In [82]:
from sklearn.metrics import classification_report,confusion_matrix

In [83]:
print(confusion_matrix(y_train,predictions_train)) #for train set

[[1097    0]
 [   2 3448]]


In [84]:
print(confusion_matrix(y_test,predictions_test)) #for test set

[[ 486   16]
 [  10 1438]]


In [85]:
print(classification_report(y_train,predictions_train))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00      1097
          1       1.00      1.00      1.00      3450

avg / total       1.00      1.00      1.00      4547



In [86]:
print(classification_report(y_test,predictions_test))

             precision    recall  f1-score   support

          0       0.98      0.97      0.97       502
          1       0.99      0.99      0.99      1448

avg / total       0.99      0.99      0.99      1950



# Random Forest Classifier

In [87]:
from sklearn.ensemble import RandomForestClassifier

In [88]:
rfc = RandomForestClassifier()

In [89]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

# Predictions and Evaluations Random Forest

In [90]:
rfc_pred_train = rfc.predict(X_train)
rfc_pred_test = rfc.predict(X_test)

In [91]:
print(confusion_matrix(y_train,rfc_pred_train))

[[1095    2]
 [   1 3449]]


In [92]:
print(confusion_matrix(y_test,rfc_pred_test))

[[ 495    7]
 [   9 1439]]


In [93]:
print(classification_report(y_train,rfc_pred_train))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00      1097
          1       1.00      1.00      1.00      3450

avg / total       1.00      1.00      1.00      4547



In [94]:
print(classification_report(y_test,rfc_pred_test))

             precision    recall  f1-score   support

          0       0.98      0.99      0.98       502
          1       1.00      0.99      0.99      1448

avg / total       0.99      0.99      0.99      1950

